#!/bin/bash -xe

MONGODB_URL=${OPENSHIFT_MONGODB_DB_URL}${OPENSHIFT_APP_NAME}

PATH=${OPENSHIFT_REPO_DIR}node_modules/.bin:$PATH

chatwork-to-slack \
    --chatwork-room-id=$CHATWORK_ROOM_ID \
    --chatwork-api-token=$CHATWORK_API_TOKEN \
    --slack-webhook-url=$SLACK_WEBHOOK_URL \
    --slack-channel=$SLACK_CHANNEL_NAME \
    --slack-icon-url=$SLACK_ICON_URL \
    --mongodb-url=$MONGODB_URL

chatwork-to-slack \
    --chatwork-room-id=$CHATWORK_ROOM_ID2 \
    --chatwork-api-token=$CHATWORK_API_TOKEN \
    --slack-webhook-url=$SLACK_WEBHOOK_URL \
    --slack-channel=$SLACK_CHANNEL_NAME2 \
    --slack-icon-url=$SLACK_ICON_URL \
    --mongodb-url=$MONGODB_URL

chatwork-to-slack \
    --chatwork-room-id=$CHATWORK_ROOM_ID3 \
    --chatwork-api-token=$CHATWORK_API_TOKEN \
    --slack-webhook-url=$SLACK_WEBHOOK_URL \
    --slack-channel=$SLACK_CHANNEL_NAME3 \
    --slack-icon-url=$SLACK_ICON_URL \
    --mongodb-url=$MONGODB_URL

chatwork-to-slack \
    --chatwork-room-id=$CHATWORK_ROOM_ID4 \
    --chatwork-api-token=$CHATWORK_API_TOKEN \
    --slack-webhook-url=$SLACK_WEBHOOK_URL \
    --slack-channel=$SLACK_CHANNEL_NAME4 \
    --slack-icon-url=$SLACK_ICON_URL \
    --mongodb-url=$MONGODB_URL
